#server:
#  port: 8090
#  servlet:
#    context-path: /service
#spring:
#  application:
#    name: billowing-service
#  cloud:
#    nacos:
#      discovery:
#        server-addr: 127.0.0.1:8848
#  datasource:
#    dynamic:
#      primary: admin
#      strict: false
#      datasource:
#        admin:
#          url: jdbc:mysql://localhost:3306/sc_admin?serverTimezone=UTC&useUnicode=true&characterEncoding=utf8
#          username: root
#          password: 123456
#          driver-class-name: com.mysql.jdbc.Driver
#  redis:
#    password:
#    lettuce:
#      pool:
#        max-active: 5000
#        max-wait: -1
#        max-idle: 30
#        min-idle: 5
#    timeout: 50000
#    host: 129.168.40.129
#    port: 6379
#
##mybatis
#mybatis-plus:
#  mapper-locations: classpath:/mapper/*Mapper.xml
#  global-config:
#    # 数据库相关配置
#    db-config:
#      #主键类型  AUTO:"数据库ID自增", INPUT:"用户输入ID",ID_WORKER:"全局唯一ID (数字类型唯一ID)", UUID:"全局唯一ID UUID";
#      id-type: id_worker
#      #字段策略 IGNORED:"忽略判断",NOT_NULL:"非 NULL 判断"),NOT_EMPTY:"非空判断"
#      field-strategy: not_empty
#      #驼峰下划线转换
#      column-underline: true
#      #数据库大写下划线转换
#      #capital-mode: true
#      #逻辑删除配置
#      logic-delete-value: 0
#      logic-not-delete-value: 1
#      db-type: h2
#    #刷新mapper 调试神器
#    refresh: true
#  # 原生配置
#  configuration:
#    map-underscore-to-camel-case: true
#    cache-enabled: false
#
#logging:
#  config: classpath:logback.xml